spring.application.name=likeherotozero

# =====================
# DATABASE (MySQL)
# =====================
spring.datasource.url=jdbc:mysql://localhost:3306/likeherotozero
spring.datasource.username=root
spring.datasource.password=DEIN_PASSWORT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================
# JPA / HIBERNATE
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =====================
# INIT (data.sql)
# =====================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true